name: Pre-release

on:
  workflow_dispatch:

jobs:
  Pre-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Poetry
        run: pip install poetry

      - name: Bump version and create GitHub pre-release
        run: |
          NEW_VERSION=$(poetry version prerelease --short)
          git add pyproject.toml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Bump version to $NEW_VERSION"
          git push origin ${{ github.ref_name }}
          gh release create "v$NEW_VERSION" --target ${{ github.ref_name }} --generate-notes --prerelease
