name: Release

on:
  push:
    branches: [main]

jobs:
  Release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Poetry
        run: pip install poetry

      - name: Create GitHub release
        id: release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION=$(poetry version --short)
          gh release create "v$VERSION" --target ${{ github.ref_name }} --generate-notes

      - name: Bump version
        run: |
          NEW_VERSION=$(poetry version patch --short)
          git add pyproject.toml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Bump version to $NEW_VERSION"
          git push origin ${{ github.ref_name }}